if (NOT LLVM_FOUND)
    message(FATAL_ERROR "no llvm found")
endif(NOT LLVM_FOUND)

# find a clang lib
MACRO(find_clang_lib LIB_NAME)
    find_library(CLANG_${LIB_NAME}_LIB ${LIB_NAME} ${LLVM_LIBRARY_DIRS})
    if (CLANG_${LIB_NAME}_LIB)
        list(APPEND CLANG_LIBS ${CLANG_${LIB_NAME}_LIB})
    endif(CLANG_${LIB_NAME}_LIB)
ENDMACRO(find_clang_lib)

find_clang_lib(clangFrontend)
find_clang_lib(clangDriver)
find_clang_lib(clangCodeGen)
find_clang_lib(clangEdit)
find_clang_lib(clangSema)
find_clang_lib(clangChecker)
find_clang_lib(clangAnalysis)
find_clang_lib(clangRewrite)
find_clang_lib(clangAST)
find_clang_lib(clangParse)
find_clang_lib(clangLex)
find_clang_lib(clangBasic)
find_clang_lib(clangASTMatchers)
find_clang_lib(clangFrontendTool)
find_clang_lib(clangRewriteFrontend)
find_clang_lib(clangStaticAnalyzerFrontend)
find_clang_lib(clangStaticAnalyzerCheckers)
find_clang_lib(clangStaticAnalyzerCore)
find_clang_lib(clangSerialization)
find_clang_lib(clangToolingCore)
find_clang_lib(clangTooling)
find_clang_lib(clangFormat)

message(STATUS "clang libraries: ${CLANG_LIBS}")
